### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by ilenia6** [marcelauliano/MitoHiFi#110]
Hi, 
I am trying to run MitoHiFi on my data, starting from assembled contigs of a nematode species.
However, it only produces a <contig_id>.mitogenome.fa file, and the workflow interrupts with a "ValueError: max() arg is an empty sequence" which is related to tRNAs search.

Does anyone have any idea?

**Comment by GiacomoGlotzer** [comment]
I'm having the same issue.

**Comment by mahajrod** [comment]
Confirm issue for both local installation and docker...

**Comment by josieparis** [comment]
I am also having this issue ... can't seem to fix it

**Comment by Tsylvester8** [comment]
Hi all,

I also have the same error when trying to run mitohifi using a local installation. I installed dependencies in a Conda environment and cloned the mitohifi repository. Installed MitoFinder outside of the Conda environment as well. For me that seemed not to work and produce the same error. However, I was able to get mitohifi via singularity and that worked well. 

Following this comment (https://github.com/marcelauliano/MitoHiFi/issues/104#issue-2562605970) I build a local copy docker image and ran mitohifi as bellow: 

```
working_dir=/path/to/output/folder
cpus=8
genetic_code=5

# run mitohifi

singularity \
 exec \
 --home $working_dir \
 /path/to/mitohifi.sif mitohifi.py \
 -c genome.fa \
 -f reference.fasta \
 -g reference.gb \
 -t $cpus \
 -o $genetic_code

```

Create your working directory and put the assembly and reference files into it. And when running singularity set your working directory as the home directory. I had to do this because the home directory singularity setting is in a different partition and I cannot access these assembly files from that location. (There might be other workarounds to resolve this issue, but this has worked for me =)). 

e.g. without the --home argument the default $HOME is /home/terrence but my files are in /scratch/terrence/projects/

I have not worked on raw reads, but I expect this to work the same. All this was done in a computing cluster which use SLURM.

Hope this helps! 

Best wishes,
Terrence

**Comment by StefanoLonardi** [comment]
I am having the same problem, and I am using apptainer (the equivalent of singularity). There is no problem mapping the home directory.

```
$ apptainer exec --home /home/stelo/babesia_odocoilei mitohifi_master.sif mitohifi.py -r ./reads/A2deertth.unmapped.fasta -f ./BdivROUENmito.fasta -g ./BdivROUENmito.gbk -t 64 -o 4
INFO:    /etc/singularity/ exists; cleanup by system administrator is not complete (see https://apptainer.org/docs/admin/latest/singularity_migration.html)
2025-03-04 17:42:16 [INFO] Welcome to MitoHifi v2. Starting pipeline...
2025-03-04 17:42:16 [INFO] Length of related mitogenome is: 6323 bp
2025-03-04 17:42:16 [INFO] Number of genes on related mitogenome: 11
2025-03-04 17:42:16 [INFO] Running MitoHifi pipeline in reads mode...
2025-03-04 17:42:16 [INFO] 1. First we map your Pacbio HiFi reads to the close-related mitogenome
2025-03-04 17:42:16 [INFO] minimap2 -t 64 --secondary=no -ax map-hifi ./BdivROUENmito.fasta ./reads/A2deertth.unmapped.fasta | samtools view -@ 64 -b -F4 -F 0x800 -o reads.HiFiMapped.bam
2025-03-04 17:42:38 [INFO] 2. Now we filter out any mapped reads that are larger than the reference mitogenome to avoid NUMTS
2025-03-04 17:42:38 [INFO] 2.1 First we convert the mapped reads from BAM to FASTA format:
2025-03-04 17:42:38 [INFO] samtools fasta reads.HiFiMapped.bam > gbk.HiFiMapped.bam.fasta
2025-03-04 17:42:39 [INFO] Total number of mapped reads: 7447
2025-03-04 17:42:39 [INFO] 2.2 Then we filter reads that are larger than 6323 bp
2025-03-04 17:42:39 [INFO] Number of filtered reads: 705
2025-03-04 17:42:39 [INFO] 3. Now let's run hifiasm to assemble the mapped and filtered reads!
2025-03-04 17:42:39 [INFO] hifiasm --primary -t 64 -f 0 -o gbk.HiFiMapped.bam.filtered.assembled gbk.HiFiMapped.bam.filtered.fasta
cat: gbk.HiFiMapped.bam.filtered.assembled.a_ctg.fa: No such file or directory
2025-03-04 17:42:40 [INFO] 4. Let's run the blast of the contigs versus the close-related mitogenome
2025-03-04 17:42:40 [INFO] 4.1. Creating BLAST database:
2025-03-04 17:42:40 [INFO] makeblastdb -in ./BdivROUENmito.fasta -dbtype nucl
2025-03-04 17:42:41 [INFO] Makeblastdb done.
2025-03-04 17:42:41 [INFO] 4.2. Running blast of contigs against close-related mitogenome:
2025-03-04 17:42:41 [INFO] blastn -query hifiasm.contigs.fasta -db ./BdivROUENmito.fasta -num_threads 64 -out contigs.blastn -outfmt 6 std qlen slen
2025-03-04 17:42:41 [INFO] Blast done.
2025-03-04 17:42:41 [INFO] 5. Filtering BLAST output to select target sequences
2025-03-04 17:42:41 [INFO] Filtering thresholds applied:
2025-03-04 17:42:41 [INFO] Minimum query percentage = 50
2025-03-04 17:42:41 [INFO] Minimum query length = 80% subject length
2025-03-04 17:42:41 [INFO] Maximum query length = 5 times subject length
2025-03-04 17:42:41 [INFO] Filtering BLAST finished. A list of the filtered contigs was saved on ./contigs_filtering/contigs_ids.txt file
2025-03-04 17:42:41 [INFO] 6. Now we are going to circularize, annotate and rotate each filtered contig. Those are potential mitogenome(s).
2025-03-04 17:42:41 [INFO] Annotation will be done using MitoFinder (default)
2025-03-04 17:42:41 [INFO] Working with contig ptg000002l
2025-03-04 17:42:41 [INFO] Working with contig ptg000001l
2025-03-04 17:42:41 [INFO] Started ptg000002l circularization
2025-03-04 17:42:41 [INFO] Started ptg000001l circularization
2025-03-04 17:42:42 [INFO] ptg000001l circularization done. Circularization info saved on ./potential_contigs/ptg000001l/ptg000001l.circularisationCheck.txt
2025-03-04 17:42:42 [INFO] Started ptg000001l (MitoFinder) annotation
2025-03-04 17:42:42 [INFO] ptg000002l circularization done. Circularization info saved on ./potential_contigs/ptg000002l/ptg000002l.circularisationCheck.txt
2025-03-04 17:42:42 [INFO] Started ptg000002l (MitoFinder) annotation
2025-03-04 17:42:45 [INFO] ptg000001l annotation done. Annotation log saved on ./potential_contigs/ptg000001l/ptg000001l.annotation_MitoFinder.log
/opt/MitoHiFi/src/parallel_annotation.py:69: UserWarning: Contig ptg000001l does not have an annotation file, check MitoFinder's log
  warnings.warn("Contig "+ contig_id + " does not have an annotation file, check MitoFinder's log")
2025-03-04 17:42:46 [INFO] ptg000002l annotation done. Annotation log saved on ./potential_contigs/ptg000002l/ptg000002l.annotation_MitoFinder.log
/opt/MitoHiFi/src/parallel_annotation.py:69: UserWarning: Contig ptg000002l does not have an annotation file, check MitoFinder's log
  warnings.warn("Contig "+ contig_id + " does not have an annotation file, check MitoFinder's log")
Traceback (most recent call last):
  File "/opt/MitoHiFi/src/mitohifi.py", line 566, in <module>
    main()
  File "/opt/MitoHiFi/src/mitohifi.py", line 303, in main
    tRNA_ref = fetch.get_ref_tRNA()
  File "/opt/MitoHiFi/src/fetch.py", line 48, in get_ref_tRNA
    reference_tRNA = max(tRNAs, key=tRNAs.get)
ValueError: max() arg is an empty sequence
```

**Comment by artorias111** [comment]
I'm having the same issue on singularity as well.

**Comment by yuzhenpeng** [comment]
ValueError: max() arg is an empty sequence

how to deal with it？

**Comment by narzouni** [comment]
I am having the same error too when running it using singularity. It looks like the error occurs due to failed annotation. That error is maybe related to the conda env inside the container because I am getting this error.

         /opt/conda/envs/mitos_env/bin/python: error while loading shared libraries: libpython2.7.so.1.0: cannot open shared object file: No such file or directory

I actually created another issue #120 which is very related.

**Comment by Abieskawa** [comment]
Hello everyone,
It seems like the docker from this repository was broken somehow. However, the container in the docker hub seems to work well.
I leave the comment in this issue (https://github.com/marcelauliano/MitoHiFi/issues/120#issuecomment-2832114739). Maybe you can take a look at it.

**Comment by AdamStuckert** [comment]
I am also having this problem with at least four different versions pulled from docker (via singularity) and run in singularity. This includes the suggestion from Abieskawa in [#120](https://github.com/marcelauliano/MitoHiFi/issues/120#issuecomment-2832114739) For me, this error is driven by a failed annotation using `MitoFinder`. The MitoHiFi software currently creates _all empty files_ within the directories for each directory. This causes MitoFinder to fail to annotate because there are no sequences.

End of logfile from mitofinder:

```
ERROR: MitoFinder didn't found any nucleotide sequence in the reference(s) file(s).
Aborting
```

**Comment by artorias111** [comment]
I was able to fix the issue by using the [findMitoReference.py](https://github.com/marcelauliano/MitoHiFi/blob/master/src/findMitoReference.py) script instead of manually downloading the reference myself from Genbank. I'm not sure if it's something to do with file parsing. Works both on the Docker/Singularity build and the manual install when the script is used. Hope this helps someone who ends up here!

Here's the code I implemented if you're curious on the parameters used: https://github.com/artorias111/mitohifi_nf/blob/main/modules/find_mito_ref.nf
