### ISSUE TITLE
singularity use error, can't write

### ISSUE THREAD

**Issue by bishopia** [marcelauliano/MitoHiFi#25]
Hi,
Thanks for setting up singularity use for this software! I'm having trouble implementing due to an error related to writing intermediate files during the minimap2 step. All my inputs are properly referred to with the /mnt prefix, but it looks like the minimap2 output2 can't write out because the prefix isn't there, hence path is incorrect. Do you have any thoughts about the below input or error output? Any help much appreciated. the container i'm using i grabbed from dockerhub, most used option there: https://hub.docker.com/r/biocontainers/mitohifi.

```
singularity exec --no-home -B $PWD:/mnt mitohifi_2.2.sif mitohifi.py -r /mnt/aact_ccs.fa -f /mnt/Cgra_MW435847.1.fa -g /mnt/Cgra_MW435847.1.gb -t 8 -o /mnt/test
2022-09-02 10:43:46 [INFO] Welcome to MitoHifi v2. Starting pipeline...
2022-09-02 10:43:46 [INFO] Length of related mitogenome is: 34970 bp
2022-09-02 10:43:46 [INFO] Number of genes on related mitogenome: 59
2022-09-02 10:43:46 [INFO] Running MitoHifi pipeline in reads mode...
2022-09-02 10:43:46 [INFO] 1. First we map your Pacbio HiFi reads to the close-related mitogenome
2022-09-02 10:43:46 [INFO] minimap2 -t 8 --secondary=no -ax map-pb /mnt/Cgra_MW435847.1.fa /mnt/aact_ccs.fa | samtools view -@ 8 -S -b -F4 -F 0x800 > reads.HiFiMapped.bam
Traceback (most recent call last):
  File "/bin/MitoHiFi/mitohifi.py", line 377, in <module>
    main()
  File "/bin/MitoHiFi/mitohifi.py", line 91, in main
    mapped_reads_f = open("reads.HiFiMapped.bam", "w")
OSError: [Errno 30] Read-only file system: 'reads.HiFiMapped.bam'
```

**Comment by marcelauliano** [comment]
Hi @bishopia have you tested mapping with a different reference? I'm suspicious that this is not a singularity error, rather its possible you are just not finding any mappings. Let me know what you think

**Comment by bishopia** [comment]
I tried with another mitogenome i pulled with findMitoReference.py, no luck, getting same error. I've also tried with contigs assembled (IPA) from my hifi reads, got this error instead:

```
(miniconda3)[ibishop@node1363 mitohifi]$ singularity exec --no-home -B $PWD:/mnt mitohifi_2.2.sif mitohifi.py -c /mnt/final.p_ctg.fasta -f /mnt/DQ186202.1.fasta -g /mnt/DQ186202.1.gb -t 8 -o /mnt/test
2022-09-05 09:50:06 [INFO] Welcome to MitoHifi v2. Starting pipeline...
2022-09-05 09:50:06 [INFO] Length of related mitogenome is: 43827 bp
2022-09-05 09:50:06 [INFO] Number of genes on related mitogenome: 62
2022-09-05 09:50:06 [INFO] Running MitoHifi pipeline in contigs mode...
2022-09-05 09:50:06 [INFO] 1. Fixing potentially conflicting FASTA headers
Traceback (most recent call last):
  File "/bin/MitoHiFi/mitohifi.py", line 377, in <module>
    main()
  File "/bin/MitoHiFi/mitohifi.py", line 165, in main
    fixContigHeaders.fix_headers(original_contigs, "fixed_header_contigs.fasta")
  File "/bin/MitoHiFi/fixContigHeaders.py", line 7, in fix_headers
    with open(fasta_out, "a") as f2:
OSError: [Errno 30] Read-only file system: 'fixed_header_contigs.fasta'
```

does this error also look like a problem with writing temp files?

**Comment by marcelauliano** [comment]
@bishopia Bear with us please, we are all busy this week. But @ksenia-krasheninnikova will be able to help you soon!

**Comment by ksenia-krasheninnikova** [comment]
Hello @bishopia

Can you please confirm which singularity version you use? Also, as an experiment, would you consider trying to mount under another name like this `-B $PWD:/work:rw`?

Thanks

**Comment by ksenia-krasheninnikova** [comment]
Hi @bishopia

The issue might be caused by the following: 
1. When you mount `--no-home -B $PWD:/mnt` the current folder inside of the container becomes `/`
2. mitohifi uses the current folder as the output folder (-o parameter should be used to specify the <GENETIC CODE> instead - run `mitohifi.py` without parameters for the list of parameters).
3. `/` is read-only. 

For now I can suggest the following. Create the output folder (would be `test` from your example) and change into it, put the files `aact_ccs.fa`, `Cgra_MW435847.1.fa`, `Cgra_MW435847.1.gb` into it. Then mount the root folder of `$PWD` as it is, like this: if your `$PWD` is `/lustre/path/to/working/folder` then mount `-B /lustre`. 
Run mitohifi as following:

`singularity exec -B <corresponding root folder> mitohifi_2.2.sif mitohifi.py -r aact_ccs.fa -f Cgra_MW435847.1.fa -g Cgra_MW435847.1.gb -t 8 -o <genetic code for mitofinder>`


I hope this will work for you.

**Comment by bishopia** [comment]
Thanks, that was clarifying, I now see what's going on. I usually mount my working directory as /mnt inside the container, so in this instance when i can't specify output dir, it wants to write to /, which is not possible. This is all aside from fact that I mistakenly thought -o was for output, not genetic code. I finally went with this, and it seems to work:

```
singularity exec --no-home -B $PWD mitohifi_2.2.sif mitohifi.py -r aact_ccs.fa -f Cgra_MW435847.1.fa -g Cgra_MW435847.1.gb -t 1 -o 4
```

would it be possible to add a -o/--output option at some point?
thanks for your help!

**Comment by ksenia-krasheninnikova** [comment]
Hi @bishopia 

That's great to know it's working for you now.

Yes, it should be possible to add --output parameter in the later releases (@marcelauliano let's keep it in mind). 
Thanks for suggestion :)

Cheers
