### ISSUE TITLE
IndexError: single positional indexer is out-of-bounds

### ISSUE THREAD

**Issue by foala** [marcelauliano/MitoHiFi#3]
Hi,
I ran the script as per the instrcutions, but I get this error:

makeblastdb done. Running blast with CCS contigs

Blast done!

Traceback (most recent call last):
  File "scripts/parse_blast.py", line 57, in <module>
    id = (ac[(ac['%q_in_match'] > 60)].sort_values(by='%q_in_match', ascending=False)['qseqid'].iloc[0])
  File "/vggpfs/fs3/vgl/scratch/vglshare/sandbox/fal/conda/envs/mitohifi2/lib/python2.7/site-packages/pandas/core/indexing.py", line 1500, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/vggpfs/fs3/vgl/scratch/vglshare/sandbox/fal/conda/envs/mitohifi2/lib/python2.7/site-packages/pandas/core/indexing.py", line 2230, in _getitem_axis
    self._validate_integer(key, axis)
  File "/vggpfs/fs3/vgl/scratch/vglshare/sandbox/fal/conda/envs/mitohifi2/lib/python2.7/site-packages/pandas/core/indexing.py", line 2139, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds

Please assist,
Thank you

**Comment by marcelauliano** [comment]
Hey Farroq,

Can you check your contigs.blastn output? It seems to me you haven't got any blast matches and that is why you got this parsing problem. For which species are you running it for?

Also, let me confirm you pulled the Mitohifi_v2? 

I'll be uploading the Docker imagine today. So you can also run it in a singularity in case this is a software version issue.
Best,
Marcela.
