### ISSUE TITLE
Gene named in the reference file is not recognized by MitoFinder.

### ISSUE THREAD

**Issue by Surbhigrewal** [marcelauliano/MitoHiFi#44]
Hi 

I'm trying to run Mitohifi on my plant genome in contig mode. Please see attached stdout log and command used. And in addition some files and screenshots to show output so far. The error says the annotation files are not being generated and the pipeline stalls. Possibly due to genes in the reference file that are not recognised by Mitofinder even though I am using the -a plant parameter.

Each scaffold's annotation folder has a subfolder called ...mitfi_Final_results which has 1 file named scaffold.annotation.infos that says

Initial contig name: scaffold_125

Statistics for final sequence:
Length: 1169355
GC content: 43.33%
Circularization: Not found

[Mitohifi.log](https://github.com/marcelauliano/MitoHiFi/files/10467012/Mitohifi.log)
[scaffold_125.annotation_MitoFinder.log](https://github.com/marcelauliano/MitoHiFi/files/10467015/scaffold_125.annotation_MitoFinder.log)
<img width="1680" alt="Screenshot 2023-01-20 at 14 22 21" src="https://user-images.githubusercontent.com/65228014/213722701-a18b4c7f-1793-4817-972b-cbb80303733d.png">
<img width="1628" alt="Screenshot 2023-01-20 at 14 24 14" src="https://user-images.githubusercontent.com/65228014/213722715-68a62c47-9d12-4d87-8023-e523eaef8009.png">

**Comment by marcelauliano** [comment]
Hi Surbhigrewal, 
I dont think the problem is unusual genes for MitoFinder, as we have a flag for MitoFinder that tries to annotate them anyway. How many scaffolds with -c are you trying to run the pipeline with? Note that MitoHiFi is not optimised for plant species, so I'm thinking the problem seems to be elsewhere.

To test it, I'd take 2 or 3 scaffolds that you are certain are mito ones and would run it again to see what comes out.

**Comment by Surbhigrewal** [comment]
Hi Marcela,

Thanks for your reply. The initial run highlighted 21 scaffolds that are potential mitogenomes. I have tried to run the pipeline on just those 21 and get the same output. It reaches a certain point and then stops. All the annotation folders look the same and the mitofinder logs all say

Gene named "ccmC" in the reference file is not recognized by MitoFinder.
MitoFinder will try to annotate it.

Gene named "mttB" in the reference file is not recognized by MitoFinder.
MitoFinder will try to annotate it.

Gene named "orf279" in the reference file is not recognized by MitoFinder.
MitoFinder will try to annotate it.

Gene named "rps12" in the reference file is not recognized by MitoFinder.
MitoFinder will try to annotate it.

```
Gene named "rpl16" in the reference file is not recognized by MitoFinder.
MitoFinder will try to annotate it.

Gene named "atp1" in the reference file is not recognized by MitoFinder.
MitoFinder will try to annotate it.

Gene named "atp9" in the reference file is not recognized by MitoFinder.
MitoFinder will try to annotate it.

Gene named "rps3" in the reference file is not recognized by MitoFinder.
MitoFinder will try to annotate it.

Gene named "rps2" in the reference file is not recognized by MitoFinder.
MitoFinder will try to annotate it.

Gene named "nad9" in the reference file is not recognized by MitoFinder.
MitoFinder will try to annotate it.

Gene named "rpl5" in the reference file is not recognized by MitoFinder.
MitoFinder will try to annotate it.

Gene named "atp4" in the reference file is not recognized by MitoFinder.
MitoFinder will try to annotate it.

Gene named "ccmB" in the reference file is not recognized by MitoFinder.
MitoFinder will try to annotate it.

Gene named "ccmFN" in the reference file is not recognized by MitoFinder.
MitoFinder will try to annotate it.

Gene named "rps1" in the reference file is not recognized by MitoFinder.
MitoFinder will try to annotate it.

Gene named "matR" in the reference file is not recognized by MitoFinder.
MitoFinder will try to annotate it.

Gene named "rps7" in the reference file is not recognized by MitoFinder.
MitoFinder will try to annotate it.

Gene named "rps13" in the reference file is not recognized by MitoFinder.
MitoFinder will try to annotate it.

Gene named "rps4" in the reference file is not recognized by MitoFinder.
MitoFinder will try to annotate it.


WARNING: COX2 is not in the reference file. MitoFinder will not annotate this gene.
WARNING: ND1 is not in the reference file. MitoFinder will not annotate this gene.
WARNING: ND2 is not in the reference file. MitoFinder will not annotate this gene.
WARNING: ND5 is not in the reference file. MitoFinder will not annotate this gene.
WARNING: rrnL is not in the reference file. MitoFinder will not annotate this gene.
WARNING: rrnS is not in the reference file. MitoFinder will not annotate this gene.
Formatting database for mitochondrial contigs identification...
Running mitochondrial contigs identification step...

MitoFinder found a single mitochondrial contig
Checking resulting contig for circularization...

Evidences of circularization could not be found, but everyother step was successful

Creating summary statistics for the mtDNA contig
```


So probably a Mitofinder issue? Attached is the fasta file with potential mitogenomes and the reference species i got from running findMitoReference.py.

[scaffolds_mitohifi.fasta.zip](https://github.com/marcelauliano/MitoHiFi/files/10468750/scaffolds_mitohifi.fasta.zip)
[MW846284.1..zip](https://github.com/marcelauliano/MitoHiFi/files/10468785/MW846284.1.zip)

**Comment by marcelauliano** [comment]
yes, let me give a try and I'll let you know soon!

**Comment by Surbhigrewal** [comment]
HI Marcela,

Unfortunately, one contig doesn't work either.

python mitohifi.py -c scaffold_125.fasta -f MW846284.1.fasta -g MW846284.1.gb -t 8 -a plant -o 11
2023-01-27 13:33:09 [INFO] Welcome to MitoHifi v2. Starting pipeline...
2023-01-27 13:33:09 [INFO] Length of related mitogenome is: 442573 bp
2023-01-27 13:33:09 [INFO] Number of genes on related mitogenome: 58
2023-01-27 13:33:09 [INFO] Running MitoHifi pipeline in contigs mode...
2023-01-27 13:33:09 [INFO] 1. Fixing potentially conflicting FASTA headers
2023-01-27 13:33:09 [INFO] 2. Let's run the blast of the contigs versus the close-related mitogenome
2023-01-27 13:33:09 [INFO] 2.1. Creating BLAST database:
2023-01-27 13:33:09 [INFO] makeblastdb -in MW846284.1.fasta -dbtype nucl
2023-01-27 13:33:10 [INFO] Makeblastdb done.
2023-01-27 13:33:10 [INFO] 2.2. Running blast of contigs against close-related mitogenome:
2023-01-27 13:33:10 [INFO] blastn -query scaffold_125.fasta -db MW846284.1.fasta -num_threads 8 -out contigs.blastn -outfmt 6 std qlen slen
2023-01-27 13:33:12 [INFO] Blast done.
2023-01-27 13:33:12 [INFO] 3. Filtering BLAST output to select target sequences
2023-01-27 13:33:12 [INFO] Filtering thresholds applied:
2023-01-27 13:33:12 [INFO] Minimum query percentage = 50
2023-01-27 13:33:12 [INFO] Minimum query length = 0% subject length
2023-01-27 13:33:12 [INFO] Maximum query length = 10 times subject length
2023-01-27 13:33:12 [INFO] Filtering BLAST finished. A list of the filtered contigs was saved on ./contigs_filtering/contigs_ids.txt file
2023-01-27 13:33:12 [INFO] 4. Now we are going to circularize, annotate and rotate each filtered contig. Those are potential mitogenome(s).
2023-01-27 13:33:12 [INFO] Annotation will be done using MitoFinder (default)
2023-01-27 13:33:12 [INFO] Working with contig scaffold_2235
2023-01-27 13:33:12 [INFO] Started scaffold_2235 circularization
2023-01-27 13:33:14 [INFO] scaffold_2235 circularization done. Circularization info saved on ./potential_contigs/scaffold_2235/scaffold_2235.circularisationCheck.txt
2023-01-27 13:33:14 [INFO] Started scaffold_2235 (MitoFinder) annotation
Traceback (most recent call last):
  File "mitohifi.py", line 550, in <module>
    main()
  File "mitohifi.py", line 289, in main
    tRNA_ref = fetch.get_ref_tRNA()
  File "/Users/sbzsm11/OneDrive - The University of Nottingham/Alien introgression/Bioinformatics/MitoHiFi-master/fetch.py", line 40, in get_ref_tRNA
    reference_tRNA = max(tRNAs, key=tRNAs.get)
ValueError: max() arg is an empty sequence

I think mitofinder hasn't installed properly.
