### ISSUE TITLE
Example data run error: FileNotFoundError: [Errno 2] No such file or directory: 'tig00007572_1.annotation.1.individual.stats'

### ISSUE THREAD

**Issue by yangqimeng99** [marcelauliano/MitoHiFi#51]
**Respected developer：**
**hello!** 
I installed all the required dependencies for MitoHiFi using conda and also correctly installed MitoFinder. When running the provided example data with the latest version(v3.01) of the software, I encountered the following error:
```

2023-04-27 22:18:32 [INFO] 6. Now we will choose the most representative contig

Traceback (most recent call last):
  File "mitohifi.py", line 550, in <module>
    main()
  File "mitohifi.py", line 351, in main
    repr_contig_id, repr_contig_cluster = getReprContig.get_repr_contig("all_mitogenomes.rotated.fa", rel_mito_len, rel_mito_num_genes, args.t, args.d)
  File "/work/home/yang_qimeng/software/MitoHiFi-3.01/getReprContig.py", line 185, in get_repr_contig
    repr_contig_id, repr_contig_cluster = get_repr_contig_info(cdhit_out_clstr, rel_mito_len, rel_mito_num_genes, debug=debug)
  File "/work/home/yang_qimeng/software/MitoHiFi-3.01/getReprContig.py", line 85, in get_repr_contig_info
    seq_frameshifts = get_frameshift_info(seq_id)
  File "/work/home/yang_qimeng/software/MitoHiFi-3.01/getReprContig.py", line 37, in get_frameshift_info
    with open(f"{seq_id}.individual.stats", "r") as f: 
FileNotFoundError: [Errno 2] No such file or directory: 'tig00007572_1.annotation.1.individual.stats'
```
In fact, I encountered the same problem when running this software on my data, and the error message is similar to the following.

`FileNotFoundError: [Errno 2] No such file or directory: 'ptg000038l.annotation.1.individual.stats'`

Moreover, this error occurs in both v3.0 and v3.01. Can you help me resolve this issue?

Good luck!

**Comment by marcelauliano** [comment]
Hi yang, 
Can I have the exact command you ran?
Thank you

**Comment by bm-silva** [comment]
Hi Marcela, I'm having a similar issue:

```
Traceback (most recent call last):
  File "/opt/MitoHiFi/src/mitohifi.py", line 558, in <module>
    main()
  File "/opt/MitoHiFi/src/mitohifi.py", line 359, in main
    repr_contig_id, repr_contig_cluster = getReprContig.get_repr_contig("all_mitogenomes.rotated.fa", rel_mito_len, rel_mito_num_genes, args.t, args.d)
  File "/opt/MitoHiFi/src/getReprContig.py", line 197, in get_repr_contig
    repr_contig_id, repr_contig_cluster = get_repr_contig_info(cdhit_out_clstr, rel_mito_len, rel_mito_num_genes, debug=debug)
  File "/opt/MitoHiFi/src/getReprContig.py", line 97, in get_repr_contig_info
    seq_frameshifts = get_frameshift_info(seq_id)
  File "/opt/MitoHiFi/src/getReprContig.py", line 49, in get_frameshift_info
    with open(f"{seq_id}.individual.stats", "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'atg000002l.individual.stats'
```

I'm running the following command:

`docker run -u $(id -u) --rm -i -v $PBS_O_WORKDIR:/data -w /data/testes ghcr.io/marcelauliano/mitohifi:master mitohifi.py -r /data/rawdata/ITV48896.fasta -f /data/assembly/NC_037857.1.fasta -g /data/assembly/NC_037857.1.gb -t 8 -o 2 --mitos`

The pipeline works without the --mitos tag. I'm attaching the log file as well
[logs.txt](https://github.com/marcelauliano/MitoHiFi/files/12358999/logs.txt)

**Comment by marcelauliano** [comment]
Hi bm-silva, 
Thanks for the info. We'll look into it and let you know soon.

**Comment by jgnunes** [comment]
Hi @bm-silva, can you share your tree of files? You can run the `tree` command in your working directory and paste the result here.

Also, can you double check if there already was a MITOS installation in your environment before running the container? Maybe run `which runmitos.py` and tell me if it shows anything. 

Last but not least, would you be able to share your input `ITV48896.fasta` file with us? Then I could try to reproduce the error from here to try to debug it.  

Best,

**Comment by bm-silva** [comment]
hi @jgnunes, here is the following tree:

```
.
├── all_contigs.circularisationCheck.txt
├── all_mitogenomes.rotated.aligned.aln
├── all_mitogenomes.rotated.fa
├── atg000001l.annotation
│   ├── blast
│   │   ├── nuc
│   │   │   ├── sequence.fas-0.OH.blast
│   │   │   └── sequence.fas-8467.OH.blast
│   │   ├── prot
│   │   │   ├── sequence.fas-0.atp6.blast
│   │   │   ├── sequence.fas-0.atp8.blast
│   │   │   ├── sequence.fas-0.atp9.blast
│   │   │   ├── sequence.fas-0.cob.blast
│   │   │   ├── sequence.fas-0.cox1.blast
│   │   │   ├── sequence.fas-0.cox2.blast
│   │   │   ├── sequence.fas-0.cox3.blast
│   │   │   ├── sequence.fas-0.dpo.blast
│   │   │   ├── sequence.fas-0.lagli.blast
│   │   │   ├── sequence.fas-0.msh1.blast
│   │   │   ├── sequence.fas-0.mttb.blast
│   │   │   ├── sequence.fas-0.nad1.blast
│   │   │   ├── sequence.fas-0.nad2.blast
│   │   │   ├── sequence.fas-0.nad3.blast
│   │   │   ├── sequence.fas-0.nad4.blast
│   │   │   ├── sequence.fas-0.nad4l.blast
│   │   │   ├── sequence.fas-0.nad5.blast
│   │   │   ├── sequence.fas-0.nad6.blast
│   │   │   ├── sequence.fas-8467.atp6.blast
│   │   │   ├── sequence.fas-8467.atp8.blast
│   │   │   ├── sequence.fas-8467.atp9.blast
│   │   │   ├── sequence.fas-8467.cob.blast
│   │   │   ├── sequence.fas-8467.cox1.blast
│   │   │   ├── sequence.fas-8467.cox2.blast
│   │   │   ├── sequence.fas-8467.cox3.blast
│   │   │   ├── sequence.fas-8467.dpo.blast
│   │   │   ├── sequence.fas-8467.lagli.blast
│   │   │   ├── sequence.fas-8467.msh1.blast
│   │   │   ├── sequence.fas-8467.mttb.blast
│   │   │   ├── sequence.fas-8467.nad1.blast
│   │   │   ├── sequence.fas-8467.nad2.blast
│   │   │   ├── sequence.fas-8467.nad3.blast
│   │   │   ├── sequence.fas-8467.nad4.blast
│   │   │   ├── sequence.fas-8467.nad4l.blast
│   │   │   ├── sequence.fas-8467.nad5.blast
│   │   │   └── sequence.fas-8467.nad6.blast
│   │   └── stst.dat
│   ├── ignored.mitos
│   ├── mitfi-global
│   │   ├── sequence.fas-0_Intron_gpI.cmout
│   │   ├── sequence.fas-0_Intron_gpII.cmout
│   │   ├── sequence.fas-0_intronout.nc
│   │   ├── sequence.fas-0_OL.cmout
│   │   ├── sequence.fas-0_rep_originout.nc
│   │   ├── sequence.fas-0_rRNAout.nc
│   │   ├── sequence.fas-0_rrnL.cmout
│   │   ├── sequence.fas-0_rrnS.cmout
│   │   ├── sequence.fas-0_trnA.cmout
│   │   ├── sequence.fas-0_tRNAout.nc
│   │   ├── sequence.fas-0_trnC.cmout
│   │   ├── sequence.fas-0_trnD.cmout
│   │   ├── sequence.fas-0_trnE.cmout
│   │   ├── sequence.fas-0_trnF.cmout
│   │   ├── sequence.fas-0_trnG.cmout
│   │   ├── sequence.fas-0_trnH.cmout
│   │   ├── sequence.fas-0_trnI.cmout
│   │   ├── sequence.fas-0_trnK.cmout
│   │   ├── sequence.fas-0_trnL1.cmout
│   │   ├── sequence.fas-0_trnL2.cmout
│   │   ├── sequence.fas-0_trnM.cmout
│   │   ├── sequence.fas-0_trnN.cmout
│   │   ├── sequence.fas-0_trnP.cmout
│   │   ├── sequence.fas-0_trnQ.cmout
│   │   ├── sequence.fas-0_trnR.cmout
│   │   ├── sequence.fas-0_trnS1.cmout
│   │   ├── sequence.fas-0_trnS2.cmout
│   │   ├── sequence.fas-0_trnT.cmout
│   │   ├── sequence.fas-0_trnV.cmout
│   │   ├── sequence.fas-0_trnW.cmout
│   │   ├── sequence.fas-0_trnY.cmout
│   │   ├── sequence.fas-8467_Intron_gpI.cmout
│   │   ├── sequence.fas-8467_Intron_gpII.cmout
│   │   ├── sequence.fas-8467_intronout.nc
│   │   ├── sequence.fas-8467_OL.cmout
│   │   ├── sequence.fas-8467_rep_originout.nc
│   │   ├── sequence.fas-8467_rRNAout.nc
│   │   ├── sequence.fas-8467_rrnL.cmout
│   │   ├── sequence.fas-8467_rrnS.cmout
│   │   ├── sequence.fas-8467_trnA.cmout
│   │   ├── sequence.fas-8467_tRNAout.nc
│   │   ├── sequence.fas-8467_trnC.cmout
│   │   ├── sequence.fas-8467_trnD.cmout
│   │   ├── sequence.fas-8467_trnE.cmout
│   │   ├── sequence.fas-8467_trnF.cmout
│   │   ├── sequence.fas-8467_trnG.cmout
│   │   ├── sequence.fas-8467_trnH.cmout
│   │   ├── sequence.fas-8467_trnI.cmout
│   │   ├── sequence.fas-8467_trnK.cmout
│   │   ├── sequence.fas-8467_trnL1.cmout
│   │   ├── sequence.fas-8467_trnL2.cmout
│   │   ├── sequence.fas-8467_trnM.cmout
│   │   ├── sequence.fas-8467_trnN.cmout
│   │   ├── sequence.fas-8467_trnP.cmout
│   │   ├── sequence.fas-8467_trnQ.cmout
│   │   ├── sequence.fas-8467_trnR.cmout
│   │   ├── sequence.fas-8467_trnS1.cmout
│   │   ├── sequence.fas-8467_trnS2.cmout
│   │   ├── sequence.fas-8467_trnT.cmout
│   │   ├── sequence.fas-8467_trnV.cmout
│   │   ├── sequence.fas-8467_trnW.cmout
│   │   └── sequence.fas-8467_trnY.cmout
│   ├── result.bed
│   ├── result.faa
│   ├── result.fas
│   ├── result.geneorder
│   ├── result.gff
│   ├── result.mitos
│   ├── result.old.gff
│   ├── result_RC.gff
│   ├── result.seq
│   ├── sequence.fas-0
│   ├── sequence.fas-8467
│   └── stst.dat
├── atg000001l.circularisationCheck.txt
├── atg000001l.circularization_check.blast.tsv
├── atg000001l.mito.fa
├── atg000001l.mito.fa.nhr
├── atg000001l.mito.fa.nin
├── atg000001l.mito.fa.nsq
├── atg000001l.mitogenome.fa
├── atg000001l.mitogenome_RC.fasta
├── atg000001l.mitogenome.rotated.fa
├── atg000001l.trnas
├── atg000002l.annotation
│   ├── blast
│   │   ├── nuc
│   │   │   ├── sequence.fas-0.OH.blast
│   │   │   └── sequence.fas-8546.OH.blast
│   │   ├── prot
│   │   │   ├── sequence.fas-0.atp6.blast
│   │   │   ├── sequence.fas-0.atp8.blast
│   │   │   ├── sequence.fas-0.atp9.blast
│   │   │   ├── sequence.fas-0.cob.blast
│   │   │   ├── sequence.fas-0.cox1.blast
│   │   │   ├── sequence.fas-0.cox2.blast
│   │   │   ├── sequence.fas-0.cox3.blast
│   │   │   ├── sequence.fas-0.dpo.blast
│   │   │   ├── sequence.fas-0.lagli.blast
│   │   │   ├── sequence.fas-0.msh1.blast
│   │   │   ├── sequence.fas-0.mttb.blast
│   │   │   ├── sequence.fas-0.nad1.blast
│   │   │   ├── sequence.fas-0.nad2.blast
│   │   │   ├── sequence.fas-0.nad3.blast
│   │   │   ├── sequence.fas-0.nad4.blast
│   │   │   ├── sequence.fas-0.nad4l.blast
│   │   │   ├── sequence.fas-0.nad5.blast
│   │   │   ├── sequence.fas-0.nad6.blast
│   │   │   ├── sequence.fas-8546.atp6.blast
│   │   │   ├── sequence.fas-8546.atp8.blast
│   │   │   ├── sequence.fas-8546.atp9.blast
│   │   │   ├── sequence.fas-8546.cob.blast
│   │   │   ├── sequence.fas-8546.cox1.blast
│   │   │   ├── sequence.fas-8546.cox2.blast
│   │   │   ├── sequence.fas-8546.cox3.blast
│   │   │   ├── sequence.fas-8546.dpo.blast
│   │   │   ├── sequence.fas-8546.lagli.blast
│   │   │   ├── sequence.fas-8546.msh1.blast
│   │   │   ├── sequence.fas-8546.mttb.blast
│   │   │   ├── sequence.fas-8546.nad1.blast
│   │   │   ├── sequence.fas-8546.nad2.blast
│   │   │   ├── sequence.fas-8546.nad3.blast
│   │   │   ├── sequence.fas-8546.nad4.blast
│   │   │   ├── sequence.fas-8546.nad4l.blast
│   │   │   ├── sequence.fas-8546.nad5.blast
│   │   │   └── sequence.fas-8546.nad6.blast
│   │   └── stst.dat
│   ├── ignored.mitos
│   ├── mitfi-global
│   │   ├── sequence.fas-0_Intron_gpI.cmout
│   │   ├── sequence.fas-0_Intron_gpII.cmout
│   │   ├── sequence.fas-0_intronout.nc
│   │   ├── sequence.fas-0_OL.cmout
│   │   ├── sequence.fas-0_rep_originout.nc
│   │   ├── sequence.fas-0_rRNAout.nc
│   │   ├── sequence.fas-0_rrnL.cmout
│   │   ├── sequence.fas-0_rrnS.cmout
│   │   ├── sequence.fas-0_trnA.cmout
│   │   ├── sequence.fas-0_tRNAout.nc
│   │   ├── sequence.fas-0_trnC.cmout
│   │   ├── sequence.fas-0_trnD.cmout
│   │   ├── sequence.fas-0_trnE.cmout
│   │   ├── sequence.fas-0_trnF.cmout
│   │   ├── sequence.fas-0_trnG.cmout
│   │   ├── sequence.fas-0_trnH.cmout
│   │   ├── sequence.fas-0_trnI.cmout
│   │   ├── sequence.fas-0_trnK.cmout
│   │   ├── sequence.fas-0_trnL1.cmout
│   │   ├── sequence.fas-0_trnL2.cmout
│   │   ├── sequence.fas-0_trnM.cmout
│   │   ├── sequence.fas-0_trnN.cmout
│   │   ├── sequence.fas-0_trnP.cmout
│   │   ├── sequence.fas-0_trnQ.cmout
│   │   ├── sequence.fas-0_trnR.cmout
│   │   ├── sequence.fas-0_trnS1.cmout
│   │   ├── sequence.fas-0_trnS2.cmout
│   │   ├── sequence.fas-0_trnT.cmout
│   │   ├── sequence.fas-0_trnV.cmout
│   │   ├── sequence.fas-0_trnW.cmout
│   │   ├── sequence.fas-0_trnY.cmout
│   │   ├── sequence.fas-8546_Intron_gpI.cmout
│   │   ├── sequence.fas-8546_Intron_gpII.cmout
│   │   ├── sequence.fas-8546_intronout.nc
│   │   ├── sequence.fas-8546_OL.cmout
│   │   ├── sequence.fas-8546_rep_originout.nc
│   │   ├── sequence.fas-8546_rRNAout.nc
│   │   ├── sequence.fas-8546_rrnL.cmout
│   │   ├── sequence.fas-8546_rrnS.cmout
│   │   ├── sequence.fas-8546_trnA.cmout
│   │   ├── sequence.fas-8546_tRNAout.nc
│   │   ├── sequence.fas-8546_trnC.cmout
│   │   ├── sequence.fas-8546_trnD.cmout
│   │   ├── sequence.fas-8546_trnE.cmout
│   │   ├── sequence.fas-8546_trnF.cmout
│   │   ├── sequence.fas-8546_trnG.cmout
│   │   ├── sequence.fas-8546_trnH.cmout
│   │   ├── sequence.fas-8546_trnI.cmout
│   │   ├── sequence.fas-8546_trnK.cmout
│   │   ├── sequence.fas-8546_trnL1.cmout
│   │   ├── sequence.fas-8546_trnL2.cmout
│   │   ├── sequence.fas-8546_trnM.cmout
│   │   ├── sequence.fas-8546_trnN.cmout
│   │   ├── sequence.fas-8546_trnP.cmout
│   │   ├── sequence.fas-8546_trnQ.cmout
│   │   ├── sequence.fas-8546_trnR.cmout
│   │   ├── sequence.fas-8546_trnS1.cmout
│   │   ├── sequence.fas-8546_trnS2.cmout
│   │   ├── sequence.fas-8546_trnT.cmout
│   │   ├── sequence.fas-8546_trnV.cmout
│   │   ├── sequence.fas-8546_trnW.cmout
│   │   └── sequence.fas-8546_trnY.cmout
│   ├── result.bed
│   ├── result.faa
│   ├── result.fas
│   ├── result.geneorder
│   ├── result.gff
│   ├── result.mitos
│   ├── result.old.gff
│   ├── result.seq
│   ├── sequence.fas-0
│   ├── sequence.fas-8546
│   └── stst.dat
├── atg000002l.circularisationCheck.txt
├── atg000002l.circularization_check.blast.tsv
├── atg000002l.mito.fa
├── atg000002l.mito.fa.nhr
├── atg000002l.mito.fa.nin
├── atg000002l.mito.fa.nsq
├── atg000002l.mitogenome.fa
├── atg000002l.mitogenome.fa.nhr
├── atg000002l.mitogenome.fa.nin
├── atg000002l.mitogenome.fa.nsq
├── atg000002l.mitogenome.rotated.fa
├── atg000002l.trnas
├── cdhit.out
├── cdhit.out.clstr
├── contigs.blastn
├── contigs_ids.txt
├── gbk.HiFiMapped.bam.fasta
├── gbk.HiFiMapped.bam.filtered.assembled.a_ctg.fa
├── gbk.HiFiMapped.bam.filtered.assembled.a_ctg.gfa
├── gbk.HiFiMapped.bam.filtered.assembled.a_ctg.lowQ.bed
├── gbk.HiFiMapped.bam.filtered.assembled.a_ctg.noseq.gfa
├── gbk.HiFiMapped.bam.filtered.assembled.ec.bin
├── gbk.HiFiMapped.bam.filtered.assembled.ovlp.reverse.bin
├── gbk.HiFiMapped.bam.filtered.assembled.ovlp.source.bin
├── gbk.HiFiMapped.bam.filtered.assembled.p_ctg.fa
├── gbk.HiFiMapped.bam.filtered.assembled.p_ctg.gfa
├── gbk.HiFiMapped.bam.filtered.assembled.p_ctg.lowQ.bed
├── gbk.HiFiMapped.bam.filtered.assembled.p_ctg.noseq.gfa
├── gbk.HiFiMapped.bam.filtered.assembled.p_utg.gfa
├── gbk.HiFiMapped.bam.filtered.assembled.p_utg.lowQ.bed
├── gbk.HiFiMapped.bam.filtered.assembled.p_utg.noseq.gfa
├── gbk.HiFiMapped.bam.filtered.assembled.r_utg.gfa
├── gbk.HiFiMapped.bam.filtered.assembled.r_utg.lowQ.bed
├── gbk.HiFiMapped.bam.filtered.assembled.r_utg.noseq.gfa
├── gbk.HiFiMapped.bam.filtered.fasta
├── hifiasm.contigs.fasta
├── hifiasm.log
├── ITV48896.fasta
├── job_mitohifi.pbs
├── mitohifi.err
├── mitohifi.log
├── NC_037857.1.fasta
├── NC_037857.1.fasta.nhr
├── NC_037857.1.fasta.nin
├── NC_037857.1.fasta.nsq
├── NC_037857.1.gb
├── parsed_blast_all.txt
├── parsed_blast.txt
├── ptg000001c.annotation
│   ├── blast
│   │   ├── nuc
│   │   │   ├── sequence.fas-0.OH.blast
│   │   │   └── sequence.fas-8546.OH.blast
│   │   ├── prot
│   │   │   ├── sequence.fas-0.atp6.blast
│   │   │   ├── sequence.fas-0.atp8.blast
│   │   │   ├── sequence.fas-0.atp9.blast
│   │   │   ├── sequence.fas-0.cob.blast
│   │   │   ├── sequence.fas-0.cox1.blast
│   │   │   ├── sequence.fas-0.cox2.blast
│   │   │   ├── sequence.fas-0.cox3.blast
│   │   │   ├── sequence.fas-0.dpo.blast
│   │   │   ├── sequence.fas-0.lagli.blast
│   │   │   ├── sequence.fas-0.msh1.blast
│   │   │   ├── sequence.fas-0.mttb.blast
│   │   │   ├── sequence.fas-0.nad1.blast
│   │   │   ├── sequence.fas-0.nad2.blast
│   │   │   ├── sequence.fas-0.nad3.blast
│   │   │   ├── sequence.fas-0.nad4.blast
│   │   │   ├── sequence.fas-0.nad4l.blast
│   │   │   ├── sequence.fas-0.nad5.blast
│   │   │   ├── sequence.fas-0.nad6.blast
│   │   │   ├── sequence.fas-8546.atp6.blast
│   │   │   ├── sequence.fas-8546.atp8.blast
│   │   │   ├── sequence.fas-8546.atp9.blast
│   │   │   ├── sequence.fas-8546.cob.blast
│   │   │   ├── sequence.fas-8546.cox1.blast
│   │   │   ├── sequence.fas-8546.cox2.blast
│   │   │   ├── sequence.fas-8546.cox3.blast
│   │   │   ├── sequence.fas-8546.dpo.blast
│   │   │   ├── sequence.fas-8546.lagli.blast
│   │   │   ├── sequence.fas-8546.msh1.blast
│   │   │   ├── sequence.fas-8546.mttb.blast
│   │   │   ├── sequence.fas-8546.nad1.blast
│   │   │   ├── sequence.fas-8546.nad2.blast
│   │   │   ├── sequence.fas-8546.nad3.blast
│   │   │   ├── sequence.fas-8546.nad4.blast
│   │   │   ├── sequence.fas-8546.nad4l.blast
│   │   │   ├── sequence.fas-8546.nad5.blast
│   │   │   └── sequence.fas-8546.nad6.blast
│   │   └── stst.dat
│   ├── ignored.mitos
│   ├── mitfi-global
│   │   ├── sequence.fas-0_Intron_gpI.cmout
│   │   ├── sequence.fas-0_Intron_gpII.cmout
│   │   ├── sequence.fas-0_intronout.nc
│   │   ├── sequence.fas-0_OL.cmout
│   │   ├── sequence.fas-0_rep_originout.nc
│   │   ├── sequence.fas-0_rRNAout.nc
│   │   ├── sequence.fas-0_rrnL.cmout
│   │   ├── sequence.fas-0_rrnS.cmout
│   │   ├── sequence.fas-0_trnA.cmout
│   │   ├── sequence.fas-0_tRNAout.nc
│   │   ├── sequence.fas-0_trnC.cmout
│   │   ├── sequence.fas-0_trnD.cmout
│   │   ├── sequence.fas-0_trnE.cmout
│   │   ├── sequence.fas-0_trnF.cmout
│   │   ├── sequence.fas-0_trnG.cmout
│   │   ├── sequence.fas-0_trnH.cmout
│   │   ├── sequence.fas-0_trnI.cmout
│   │   ├── sequence.fas-0_trnK.cmout
│   │   ├── sequence.fas-0_trnL1.cmout
│   │   ├── sequence.fas-0_trnL2.cmout
│   │   ├── sequence.fas-0_trnM.cmout
│   │   ├── sequence.fas-0_trnN.cmout
│   │   ├── sequence.fas-0_trnP.cmout
│   │   ├── sequence.fas-0_trnQ.cmout
│   │   ├── sequence.fas-0_trnR.cmout
│   │   ├── sequence.fas-0_trnS1.cmout
│   │   ├── sequence.fas-0_trnS2.cmout
│   │   ├── sequence.fas-0_trnT.cmout
│   │   ├── sequence.fas-0_trnV.cmout
│   │   ├── sequence.fas-0_trnW.cmout
│   │   ├── sequence.fas-0_trnY.cmout
│   │   ├── sequence.fas-8546_Intron_gpI.cmout
│   │   ├── sequence.fas-8546_Intron_gpII.cmout
│   │   ├── sequence.fas-8546_intronout.nc
│   │   ├── sequence.fas-8546_OL.cmout
│   │   ├── sequence.fas-8546_rep_originout.nc
│   │   ├── sequence.fas-8546_rRNAout.nc
│   │   ├── sequence.fas-8546_rrnL.cmout
│   │   ├── sequence.fas-8546_rrnS.cmout
│   │   ├── sequence.fas-8546_trnA.cmout
│   │   ├── sequence.fas-8546_tRNAout.nc
│   │   ├── sequence.fas-8546_trnC.cmout
│   │   ├── sequence.fas-8546_trnD.cmout
│   │   ├── sequence.fas-8546_trnE.cmout
│   │   ├── sequence.fas-8546_trnF.cmout
│   │   ├── sequence.fas-8546_trnG.cmout
│   │   ├── sequence.fas-8546_trnH.cmout
│   │   ├── sequence.fas-8546_trnI.cmout
│   │   ├── sequence.fas-8546_trnK.cmout
│   │   ├── sequence.fas-8546_trnL1.cmout
│   │   ├── sequence.fas-8546_trnL2.cmout
│   │   ├── sequence.fas-8546_trnM.cmout
│   │   ├── sequence.fas-8546_trnN.cmout
│   │   ├── sequence.fas-8546_trnP.cmout
│   │   ├── sequence.fas-8546_trnQ.cmout
│   │   ├── sequence.fas-8546_trnR.cmout
│   │   ├── sequence.fas-8546_trnS1.cmout
│   │   ├── sequence.fas-8546_trnS2.cmout
│   │   ├── sequence.fas-8546_trnT.cmout
│   │   ├── sequence.fas-8546_trnV.cmout
│   │   ├── sequence.fas-8546_trnW.cmout
│   │   └── sequence.fas-8546_trnY.cmout
│   ├── result.bed
│   ├── result.faa
│   ├── result.fas
│   ├── result.geneorder
│   ├── result.gff
│   ├── result.mitos
│   ├── result.old.gff
│   ├── result_RC.gff
│   ├── result.seq
│   ├── sequence.fas-0
│   ├── sequence.fas-8546
│   └── stst.dat
├── ptg000001c.circularisationCheck.txt
├── ptg000001c.circularization_check.blast.tsv
├── ptg000001c.mito.fa
├── ptg000001c.mito.fa.nhr
├── ptg000001c.mito.fa.nin
├── ptg000001c.mito.fa.nsq
├── ptg000001c.mitogenome.fa
├── ptg000001c.mitogenome.fa.nhr
├── ptg000001c.mitogenome.fa.nin
├── ptg000001c.mitogenome.fa.nsq
├── ptg000001c.mitogenome_RC.fasta
├── ptg000001c.mitogenome.rotated.fa
├── ptg000001c.trnas
├── ptg000002l.annotation
│   ├── blast
│   │   ├── nuc
│   │   │   ├── sequence.fas-0.OH.blast
│   │   │   └── sequence.fas-8546.OH.blast
│   │   ├── prot
│   │   │   ├── sequence.fas-0.atp6.blast
│   │   │   ├── sequence.fas-0.atp8.blast
│   │   │   ├── sequence.fas-0.atp9.blast
│   │   │   ├── sequence.fas-0.cob.blast
│   │   │   ├── sequence.fas-0.cox1.blast
│   │   │   ├── sequence.fas-0.cox2.blast
│   │   │   ├── sequence.fas-0.cox3.blast
│   │   │   ├── sequence.fas-0.dpo.blast
│   │   │   ├── sequence.fas-0.lagli.blast
│   │   │   ├── sequence.fas-0.msh1.blast
│   │   │   ├── sequence.fas-0.mttb.blast
│   │   │   ├── sequence.fas-0.nad1.blast
│   │   │   ├── sequence.fas-0.nad2.blast
│   │   │   ├── sequence.fas-0.nad3.blast
│   │   │   ├── sequence.fas-0.nad4.blast
│   │   │   ├── sequence.fas-0.nad4l.blast
│   │   │   ├── sequence.fas-0.nad5.blast
│   │   │   ├── sequence.fas-0.nad6.blast
│   │   │   ├── sequence.fas-8546.atp6.blast
│   │   │   ├── sequence.fas-8546.atp8.blast
│   │   │   ├── sequence.fas-8546.atp9.blast
│   │   │   ├── sequence.fas-8546.cob.blast
│   │   │   ├── sequence.fas-8546.cox1.blast
│   │   │   ├── sequence.fas-8546.cox2.blast
│   │   │   ├── sequence.fas-8546.cox3.blast
│   │   │   ├── sequence.fas-8546.dpo.blast
│   │   │   ├── sequence.fas-8546.lagli.blast
│   │   │   ├── sequence.fas-8546.msh1.blast
│   │   │   ├── sequence.fas-8546.mttb.blast
│   │   │   ├── sequence.fas-8546.nad1.blast
│   │   │   ├── sequence.fas-8546.nad2.blast
│   │   │   ├── sequence.fas-8546.nad3.blast
│   │   │   ├── sequence.fas-8546.nad4.blast
│   │   │   ├── sequence.fas-8546.nad4l.blast
│   │   │   ├── sequence.fas-8546.nad5.blast
│   │   │   └── sequence.fas-8546.nad6.blast
│   │   └── stst.dat
│   ├── ignored.mitos
│   ├── mitfi-global
│   │   ├── sequence.fas-0_Intron_gpI.cmout
│   │   ├── sequence.fas-0_Intron_gpII.cmout
│   │   ├── sequence.fas-0_intronout.nc
│   │   ├── sequence.fas-0_OL.cmout
│   │   ├── sequence.fas-0_rep_originout.nc
│   │   ├── sequence.fas-0_rRNAout.nc
│   │   ├── sequence.fas-0_rrnL.cmout
│   │   ├── sequence.fas-0_rrnS.cmout
│   │   ├── sequence.fas-0_trnA.cmout
│   │   ├── sequence.fas-0_tRNAout.nc
│   │   ├── sequence.fas-0_trnC.cmout
│   │   ├── sequence.fas-0_trnD.cmout
│   │   ├── sequence.fas-0_trnE.cmout
│   │   ├── sequence.fas-0_trnF.cmout
│   │   ├── sequence.fas-0_trnG.cmout
│   │   ├── sequence.fas-0_trnH.cmout
│   │   ├── sequence.fas-0_trnI.cmout
│   │   ├── sequence.fas-0_trnK.cmout
│   │   ├── sequence.fas-0_trnL1.cmout
│   │   ├── sequence.fas-0_trnL2.cmout
│   │   ├── sequence.fas-0_trnM.cmout
│   │   ├── sequence.fas-0_trnN.cmout
│   │   ├── sequence.fas-0_trnP.cmout
│   │   ├── sequence.fas-0_trnQ.cmout
│   │   ├── sequence.fas-0_trnR.cmout
│   │   ├── sequence.fas-0_trnS1.cmout
│   │   ├── sequence.fas-0_trnS2.cmout
│   │   ├── sequence.fas-0_trnT.cmout
│   │   ├── sequence.fas-0_trnV.cmout
│   │   ├── sequence.fas-0_trnW.cmout
│   │   ├── sequence.fas-0_trnY.cmout
│   │   ├── sequence.fas-8546_Intron_gpI.cmout
│   │   ├── sequence.fas-8546_Intron_gpII.cmout
│   │   ├── sequence.fas-8546_intronout.nc
│   │   ├── sequence.fas-8546_OL.cmout
│   │   ├── sequence.fas-8546_rep_originout.nc
│   │   ├── sequence.fas-8546_rRNAout.nc
│   │   ├── sequence.fas-8546_rrnL.cmout
│   │   ├── sequence.fas-8546_rrnS.cmout
│   │   ├── sequence.fas-8546_trnA.cmout
│   │   ├── sequence.fas-8546_tRNAout.nc
│   │   ├── sequence.fas-8546_trnC.cmout
│   │   ├── sequence.fas-8546_trnD.cmout
│   │   ├── sequence.fas-8546_trnE.cmout
│   │   ├── sequence.fas-8546_trnF.cmout
│   │   ├── sequence.fas-8546_trnG.cmout
│   │   ├── sequence.fas-8546_trnH.cmout
│   │   ├── sequence.fas-8546_trnI.cmout
│   │   ├── sequence.fas-8546_trnK.cmout
│   │   ├── sequence.fas-8546_trnL1.cmout
│   │   ├── sequence.fas-8546_trnL2.cmout
│   │   ├── sequence.fas-8546_trnM.cmout
│   │   ├── sequence.fas-8546_trnN.cmout
│   │   ├── sequence.fas-8546_trnP.cmout
│   │   ├── sequence.fas-8546_trnQ.cmout
│   │   ├── sequence.fas-8546_trnR.cmout
│   │   ├── sequence.fas-8546_trnS1.cmout
│   │   ├── sequence.fas-8546_trnS2.cmout
│   │   ├── sequence.fas-8546_trnT.cmout
│   │   ├── sequence.fas-8546_trnV.cmout
│   │   ├── sequence.fas-8546_trnW.cmout
│   │   └── sequence.fas-8546_trnY.cmout
│   ├── result.bed
│   ├── result.faa
│   ├── result.fas
│   ├── result.geneorder
│   ├── result.gff
│   ├── result.mitos
│   ├── result.seq
│   ├── sequence.fas-0
│   ├── sequence.fas-8546
│   └── stst.dat
├── ptg000002l.circularisationCheck.txt
├── ptg000002l.circularization_check.blast.tsv
├── ptg000002l.mito.fa
├── ptg000002l.mito.fa.nhr
├── ptg000002l.mito.fa.nin
├── ptg000002l.mito.fa.nsq
├── ptg000002l.mitogenome.fa
├── ptg000002l.mitogenome.fa.nhr
├── ptg000002l.mitogenome.fa.nin
├── ptg000002l.mitogenome.fa.nsq
├── ptg000002l.mitogenome.rotated.fa
├── ptg000002l.trnas
└── reads.HiFiMapped.bam

20 directories, 540 files
```

there is no mitos installed in my environment, so the which runmitos.py returns  no runmitos.py in $PATH.

im afraid i can not share you the fasta file. its a private work and its not yet published, sorry
