### ISSUE TITLE
[makeblastdb]

### ISSUE THREAD

**Issue by Isoris** [marcelauliano/MitoHiFi#65]
Hi, 

I just wanted to let you know that you've forgot to add blast and makeblastdb in  the dependencies.

2023-11-16 01:41:33 [INFO] 4. Let's run the blast of the contigs versus the close-related mitogenome
2023-11-16 01:41:33 [INFO] 4.1. Creating BLAST database:
2023-11-16 01:41:33 [INFO] makeblastdb -in ../../../00-INPUTS/07-MITO/C_gariepinus_mito_KT809508.fasta -dbtype nucl
Traceback (most recent call last):
  File "/tarafs/data/home/qandres/scratch/catfish/01-PROGRAMS/MitoHiFi/src/mitohifi.py", line 557, in <module>
    main()
  File "/tarafs/data/home/qandres/scratch/catfish/01-PROGRAMS/MitoHiFi/src/mitohifi.py", line 201, in main
    subprocess.run(makeblastdb_cmd, stderr=subprocess.DEVNULL, stdout=subprocess.DEVNULL)
  File "/tarafs/scratch/proj5034-AGBKU/catfish/01-PROGRAMS/miniforge3/envs/mitohifi_env/lib/python3.7/subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/tarafs/scratch/proj5034-AGBKU/catfish/01-PROGRAMS/miniforge3/envs/mitohifi_env/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/tarafs/scratch/proj5034-AGBKU/catfish/01-PROGRAMS/miniforge3/envs/mitohifi_env/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'makeblastdb': 'makeblastdb'

Best regards, 

Quentin

**Comment by marcelauliano** [comment]
Hi Quentin, if you use a docker container its all there, but you are right we forgot blast for our manual installation description and conda recipe. Thank you for letting us know
