### ISSUE TITLE
AttributeError: 'Seq' object has no attribute 'defined'

### ISSUE THREAD

**Issue by ramaniak** [marcelauliano/MitoHiFi#66]
Hello, I am getting the following error when running the tool on a human sample.  
I don't see any prior reference to this and was wondering if you have any advice on how to proceed. 

`2023-11-21 18:11:50 [INFO] 10. Building annotation plots for all contigs
Traceback (most recent call last):
  File "/opt/MitoHiFi/src/mitohifi.py", line 567, in <module>
    main()
  File "/opt/MitoHiFi/src/mitohifi.py", line 492, in main
    plot_annotation.plot_annotation("final_mitogenome.gb", "final_mitogenome.annotation.png")
  File "/opt/MitoHiFi/src/plot_annotation.py", line 38, in plot_annotation
    graphic_record = MyCustomTranslator().translate_record(in_gb)
  File "/usr/local/lib/python3.6/dist-packages/dna_features_viewer/BiopythonTranslator/BiopythonTranslatorBase.py", line 89, in translate_record
    sequence=str(record.seq) if record.seq.defined else None,
AttributeError: 'Seq' object has no attribute 'defined'`

**Comment by sbassi** [comment]
I submitted a patch where I delete the defined attribute

**Comment by sbassi** [comment]
the patch was submited to other repo, because the issue is in another script that is being called from MitoHIFI, but the error is in DnaFeaturesViewer
Here is the patch
https://github.com/Edinburgh-Genome-Foundry/DnaFeaturesViewer/pull/89
