### ISSUE TITLE
Error: Invalid literal for int() with base 16: b''

### ISSUE THREAD

**Issue by mahesh-panchal** [marcelauliano/MitoHiFi#71]
Command executed:
```
  findMitoReference.py \
      --species "Laetiporus sulphureus" \
      --outfolder . \
```
Error trace:
```
  Traceback (most recent call last):
    File "/usr/lib/python3.6/http/client.py", line 564, in _get_chunk_left
      chunk_left = self._read_next_chunk_size()
    File "/usr/lib/python3.6/http/client.py", line 531, in _read_next_chunk_size
      return int(line, 16)
  ValueError: invalid literal for int() with base 16: b''

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/usr/lib/python3.6/http/client.py", line 596, in _readinto_chunked
      chunk_left = self._get_chunk_left()
    File "/usr/lib/python3.6/http/client.py", line 566, in _get_chunk_left
      raise IncompleteRead(b'')
  http.client.IncompleteRead: IncompleteRead(0 bytes read)

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/opt/MitoHiFi/src/findMitoReference.py", line 93, in <module>
      for g in [args.species] + list(get_lineage(args.species)):
    File "/opt/MitoHiFi/src/findMitoReference.py", line 35, in get_lineage
      records = Entrez.read(handle)
    File "/usr/local/lib/python3.6/dist-packages/Bio/Entrez/__init__.py", line 508, in read
      record = handler.read(handle)
    File "/usr/local/lib/python3.6/dist-packages/Bio/Entrez/Parser.py", line 335, in read
      self.parser.ParseFile(handle)
    File "/usr/lib/python3.6/http/client.py", line 467, in read                                         
      n = self.readinto(b)
    File "/usr/lib/python3.6/http/client.py", line 501, in readinto
      return self._readinto_chunked(b)
    File "/usr/lib/python3.6/http/client.py", line 612, in _readinto_chunked
      raise IncompleteRead(bytes(b[0:total_bytes]))
  http.client.IncompleteRead: IncompleteRead(1725 bytes read)
```
container: `ghcr.io/marcelauliano/mitohifi:master` (It would be really nice if this was versioned)

**Comment by marcelauliano** [comment]
Nothing has been changed in findMitoReference.py it the latests releases. If something is changed, it will be written in the version release.

```
findMitoReference.py --species "Laetiporus sulphureus" --min_length 12000 -n 1 --outfolder .
```
working well over here with the latest container.
Best,
M.
